export const GET_USERNAME = 'GET_USERNAME';
export const VIEW_CATEGORIES = 'VIEW_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const VIEW_RECIPES = 'VIEW_RECIPES';
